# Generated by Django 5.1.6 on 2025-03-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='created_by',
        ),
    ]
