# Generated by Django 5.1.6 on 2025-03-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_count_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table_number',
            new_name='table',
        ),
    ]
